spring.application.name=IceCream-SpringBoot

# Para MySQL, cambiamos localhost a mysql (nombre del servicio en docker-compose)
spring.datasource.url=${MYSQL_URL:jdbc:mysql://mysql:3306/DB_IceCream}
spring.datasource.username=root
spring.datasource.password=Oso17
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.hibernate.ddl-auto=update

# Para MongoDB, cambiamos localhost a mongo (nombre del servicio en docker-compose)
spring.data.mongodb.uri=${MONGO_URI:mongodb://mongo:27017/heladeria_db}
server.port=8080