spring.application.name=IceCream-SpringBoot
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DB_IceCream
spring.datasource.username=sa
spring.datasource.password=Admin#
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true